# Generated by Django 5.1.7 on 2025-03-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_intermediate_xp_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='xp_level',
            field=models.CharField(choices=[('simple', 'Simple'), ('complex', 'Complexe'), ('admin', 'Admin')], default='simple', max_length=10, verbose_name="Niveau d'XP"),
        ),
    ]
