# Generated by Django 5.1.7 on 2025-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_xp_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='xp_level',
            field=models.CharField(choices=[('simple', 'Simple'), ('intermediate', 'Intermédiaire'), ('complex', 'Complexe'), ('admin', 'Admin')], default='simple', max_length=15, verbose_name="Niveau d'XP"),
        ),
    ]
