# Generated by Django 5.1.7 on 2025-03-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_xp_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, help_text='Entrez votre date de naissance (format : DD-MM-YYYY).', null=True),
        ),
    ]
