# Generated by Django 5.1.7 on 2025-04-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp_points',
            field=models.IntegerField(default=0),
        ),
    ]
