# Generated by Django 5.1.7 on 2025-03-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objConnecte', '0002_objconnecte_connected_objconnecte_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objconnecte',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='objconnecte',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='objconnecte',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitude'),
        ),
    ]
