# Generated by Django 5.1.7 on 2025-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objConnecte', '0003_alter_objconnecte_ip_alter_objconnecte_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.ImageField(default='data/type_images/default.jpg', upload_to='data/type_images/', verbose_name='Icône'),
        ),
    ]
