# Generated by Django 5.1.7 on 2025-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objConnecte', '0004_type_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='objconnecte',
            name='attente_technicien',
            field=models.BooleanField(default=False, verbose_name='Attente d’un technicien'),
        ),
        migrations.AlterField(
            model_name='objconnecte',
            name='state',
            field=models.BooleanField(default=False, verbose_name='État'),
        ),
    ]
