# Generated by Django 5.1.7 on 2025-04-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objConnecte', '0005_objconnecte_attente_technicien_and_more'),
        ('objConnecte', '000X_add_highlighted_field'),
    ]

    operations = [
    ]
