# Generated by Django 5.1.7 on 2025-04-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objConnecte', '0006_merge_20250404_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data_type', models.CharField(choices=[('energy_consumption', 'Consommation énergétique'), ('pollution_level', 'Niveau de pollution'), ('battery_level', 'Niveau de batterie'), ('battery_consumption', 'Consommation de batterie'), ('usage_count', "Nombre d'utilisations"), ('uptime', 'Temps de fonctionnement')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='kWh', max_length=20)),
                ('obj_connecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_data', to='objConnecte.objconnecte')),
            ],
            options={
                'verbose_name': "Donnée d'utilisation",
                'verbose_name_plural': "Données d'utilisation",
                'ordering': ['-timestamp'],
            },
        ),
    ]
