# Generated by Django 5.1.7 on 2025-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '000X_add_read_by_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(choices=[('#1e2a47', 'Bleu foncé (défaut)'), ('#28a745', 'Vert'), ('#dc3545', 'Rouge'), ('#ffc107', 'Jaune'), ('#17a2b8', 'Bleu clair'), ('#6610f2', 'Violet'), ('#fd7e14', 'Orange'), ('#343a40', 'Noir')], default='#1e2a47', max_length=20)),
                ('font_family', models.CharField(choices=[('Roboto, sans-serif', 'Roboto (défaut)'), ('Arial, sans-serif', 'Arial'), ('Helvetica, sans-serif', 'Helvetica'), ('Times New Roman, serif', 'Times New Roman'), ('Georgia, serif', 'Georgia'), ('Courier New, monospace', 'Courier New')], default='Roboto, sans-serif', max_length=50)),
                ('enable_animations', models.BooleanField(default=True)),
                ('site_title', models.CharField(default='StarCity', max_length=100)),
                ('footer_text', models.CharField(default='© 2025 CY_WEBSITE. Tous droits réservés.', max_length=200)),
            ],
            options={
                'verbose_name': 'Apparence du site',
                'verbose_name_plural': 'Apparence du site',
            },
        ),
    ]
